Update main_prod-drs-be.yml

diff --git a/.github/workflows/main_prod-drs-be.yml b/.github/workflows/main_prod-drs-be.yml
--- a/.github/workflows/main_prod-drs-be.yml
+++ b/.github/workflows/main_prod-drs-be.yml
@@ -1,7 +1,3 @@
-# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
-# More GitHub Actions for Azure: https://github.com/Azure/actions
-# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions
-
 name: Build and deploy Python app to Azure Web App - prod-drs-be
 
 on:
@@ -15,33 +11,34 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
 
       - name: Set up Python version
         uses: actions/setup-python@v5
         with:
           python-version: '3.9'
 
-      - name: Create and start virtual environment
-        run: |
-          python -m venv venv
-          source venv/bin/activate
-      
       - name: Install dependencies
-        run: pip install -r requirements.txt
-        
-      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
+        run: |
+          cd backend/api
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+
+      - name: Create Procfile
+        run: |
+          echo 'web: gunicorn --bind=0.0.0.0 --timeout 600 run:app --log-file -' > backend/api/Procfile
 
       - name: Zip artifact for deployment
-        run: zip release.zip ./* -r
+        run: |
+          cd backend/api
+          zip -r ../../release.zip ./* -x ".env" "__pycache__/*" "*.pyc"
 
       - name: Upload artifact for deployment jobs
         uses: actions/upload-artifact@v4
         with:
           name: python-app
-          path: |
-            release.zip
-            !venv/
+          path: release.zip
 
   deploy:
     runs-on: ubuntu-latest
@@ -50,7 +47,7 @@ jobs:
       name: 'Production'
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
     permissions:
-      id-token: write #This is required for requesting the JWT
+      id-token: write
 
     steps:
       - name: Download artifact from build job
@@ -59,9 +56,17 @@ jobs:
           name: python-app
 
       - name: Unzip artifact for deployment
-        run: unzip release.zip
+        run: unzip release.zip -d ./deploy
 
-      
+      - name: List Deployment Package Contents
+        run: |
+          echo "Listing contents of the repo root"
+          ls -la
+          echo "Listing contents of backend/api"
+          ls -la ./backend/api || echo "backend/api directory not found"
+          echo "Listing contents of deploy directory:"
+          ls -la ./deploy
+
       - name: Login to Azure
         uses: azure/login@v2
         with:
@@ -75,4 +80,4 @@ jobs:
         with:
           app-name: 'prod-drs-be'
           slot-name: 'Production'
-          
+          package: './deploy'
